version: '3.4'

services:
  pwa:
    build:
      context: ./pwa
      target: development
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    ports:
      - '443:3000'
    volumes:
      - ./pwa:/app:cached
